#ifndef X_INCLUDE_TOKENS
#define X_INCLUDE_TOKENS

#include "pp/tokens.h"

typedef enum TOKEN_TAG {
    TOK_UNDEFINED,
    TOK_OTHER,
    TOK_EOF,
    TOK_KEYWORD,
    TOK_PUNCT,
    TOK_IDENT,
    TOK_INT,
    TOK_CHR,
    TOK_STR,
} TOKEN_TAG; 

typedef enum KEYWORD_TAG {
    //statements
    KEYWORD_UNDEFINED,
    KEYWORD_IF,
    KEYWORD_ELSE,
    KEYWORD_WHILE,
    KEYWORD_DO,
    KEYWORD_FOR,
    KEYWORD_SWITCH,
    KEYWORD_CASE,
    KEYWORD_DEFAULT,
    KEYWORD_BREAK,
    KEYWORD_CONTINUE,
    KEYWORD_GOTO,
    KEYWORD_RETURN,
    KEYWORD_ASM,
    KEYWORD_SYNC,
    
    // aggregates
    KEYWORD_IMPORT,
    KEYWORD_STRUCT,
    KEYWORD_UNION,
    KEYWORD_ENUM,
    KEYWORD_CLASS,
    KEYWORD_INTERFACE,
    KEYWORD_OVERRIDE,
    
    KEYWORD_TYPEDEF,
    KEYWORD_ALIGN,
    KEYWORD_EXTERN,
    KEYWORD_AUTO,
    KEYWORD_CONST,
    KEYWORD_STATIC,
    KEYWORD_REGISTER,
    KEYWORD_IMMUTABLE,
            
    // basic types
    KEYWORD_VOID,
    KEYWORD_CHAR,
    KEYWORD_WCHAR,
    KEYWORD_SHORT,
    KEYWORD_INT,
    KEYWORD_LONG,
    KEYWORD_FLOAT,
    KEYWORD_DOUBLE,
    KEYWORD_SIGNED,
    KEYWORD_UNSIGNED,
            
    KEYWORD_SIZEOF,
} KEYWORD_TAG;

typedef enum PUNCT_TAG {
    // operators
    PUNCT_UNDEFINED,
    PUNCT_LBRACE,
    PUNCT_RBRACE,
    PUNCT_LPAREN,
    PUNCT_RPAREN,
    PUNCT_LBRACKET,
    PUNCT_RBRACKET,
    
    PUNCT_SEMICOLON,
    PUNCT_PERIOD,
    PUNCT_ELLIPSIS,
    PUNCT_COMMA,
    PUNCT_QUESTION,
    PUNCT_COLON,
    PUNCT_ARROW,
            
    PUNCT_ASSIGN,
            
    PUNCT_LT,
    PUNCT_GT,
    PUNCT_LE,
    PUNCT_GE,
    PUNCT_EQ,
    PUNCT_NEQ,
    
    PUNCT_SHL,
    PUNCT_SHR,
    PUNCT_SHLASSIGN,
    PUNCT_SHRASSIGN,
    
    PUNCT_PLUS,
    PUNCT_MIN,
    PUNCT_PLUSASSIGN,
    PUNCT_MINASSIGN,
    
    PUNCT_MUL,
    PUNCT_DIV,
    PUNCT_MOD,
    PUNCT_MULASSIGN,
    PUNCT_DIVASSIGN,
    PUNCT_MODASSIGN,
    
    PUNCT_AND,
    PUNCT_OR,
    PUNCT_XOR,
            
    PUNCT_ANDASSIGN,
    PUNCT_ORASSIGN,
    PUNCT_XORASSIGN,
    
    PUNCT_ANDAND,
    PUNCT_OROR,
            
    PUNCT_NOT,
    PUNCT_TILDE,
    
    PUNCT_PLUSPLUS,
    PUNCT_MINMIN,
    
      
    
    TOK_PREPLUSPLUS,
    TOK_PREMINMIN,
} PUNCT_TAG;
#endif /*X_INCLUDE_TOKENS*/